// Code generated by "stringer -type=Op"; DO NOT EDIT.

package spec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Pass-1]
	_ = x[Equal-2]
	_ = x[Craft-3]
	_ = x[Uncraft-4]
	_ = x[TypeOf-5]
	_ = x[SizeOf-6]
	_ = x[MaxSize-7]
	_ = x[Fingerprint-8]
	_ = x[Root-9]
	_ = x[Encode-10]
	_ = x[Decode-11]
	_ = x[ZERO-16]
	_ = x[ONE-31]
	_ = x[ArrayEmpty-32]
	_ = x[ArrayUnit-33]
	_ = x[ProductEmpty-34]
	_ = x[ProductUnit-35]
	_ = x[Concat-36]
	_ = x[MakeSum-37]
	_ = x[Which-38]
	_ = x[Field-39]
	_ = x[Slot-40]
	_ = x[Section-41]
	_ = x[Gather-42]
	_ = x[Slice-43]
	_ = x[Let-48]
	_ = x[Lazy-49]
	_ = x[Lambda-50]
	_ = x[Fractal-51]
	_ = x[Eval-52]
	_ = x[Apply-53]
	_ = x[Mux-54]
	_ = x[Branch-55]
	_ = x[Try-56]
	_ = x[Panic-57]
	_ = x[Post-64]
	_ = x[Load-65]
	_ = x[Input-80]
	_ = x[Output-81]
	_ = x[Interact-82]
	_ = x[ListFrom-112]
	_ = x[ListTo-113]
	_ = x[AnyTypeFrom-114]
	_ = x[AnyTypeTo-115]
	_ = x[AnyTypeElemType-116]
	_ = x[AnyValueFrom-117]
	_ = x[AnyValueTo-118]
	_ = x[AnyValueElemType-119]
	_ = x[Self-128]
	_ = x[LiteralKind-129]
	_ = x[LiteralAnyType-130]
	_ = x[LiteralAnyValue-131]
	_ = x[LiteralB0-136]
	_ = x[LiteralB2-137]
	_ = x[LiteralB4-138]
	_ = x[LiteralB8-139]
	_ = x[LiteralB16-140]
	_ = x[LiteralB32-141]
	_ = x[LiteralB64-142]
	_ = x[LiteralB128-143]
	_ = x[LiteralB256-144]
	_ = x[Param0-192]
	_ = x[ParamN-255]
}

const _Op_name = "UnknownPassEqualCraftUncraftTypeOfSizeOfMaxSizeFingerprintRootEncodeDecodeZEROONEArrayEmptyArrayUnitProductEmptyProductUnitConcatMakeSumWhichFieldSlotSectionGatherSliceLetLazyLambdaFractalEvalApplyMuxBranchTryPanicPostLoadInputOutputInteractListFromListToAnyTypeFromAnyTypeToAnyTypeElemTypeAnyValueFromAnyValueToAnyValueElemTypeSelfLiteralKindLiteralAnyTypeLiteralAnyValueLiteralB0LiteralB2LiteralB4LiteralB8LiteralB16LiteralB32LiteralB64LiteralB128LiteralB256Param0ParamN"

var _Op_map = map[Op]string{
	0:   _Op_name[0:7],
	1:   _Op_name[7:11],
	2:   _Op_name[11:16],
	3:   _Op_name[16:21],
	4:   _Op_name[21:28],
	5:   _Op_name[28:34],
	6:   _Op_name[34:40],
	7:   _Op_name[40:47],
	8:   _Op_name[47:58],
	9:   _Op_name[58:62],
	10:  _Op_name[62:68],
	11:  _Op_name[68:74],
	16:  _Op_name[74:78],
	31:  _Op_name[78:81],
	32:  _Op_name[81:91],
	33:  _Op_name[91:100],
	34:  _Op_name[100:112],
	35:  _Op_name[112:123],
	36:  _Op_name[123:129],
	37:  _Op_name[129:136],
	38:  _Op_name[136:141],
	39:  _Op_name[141:146],
	40:  _Op_name[146:150],
	41:  _Op_name[150:157],
	42:  _Op_name[157:163],
	43:  _Op_name[163:168],
	48:  _Op_name[168:171],
	49:  _Op_name[171:175],
	50:  _Op_name[175:181],
	51:  _Op_name[181:188],
	52:  _Op_name[188:192],
	53:  _Op_name[192:197],
	54:  _Op_name[197:200],
	55:  _Op_name[200:206],
	56:  _Op_name[206:209],
	57:  _Op_name[209:214],
	64:  _Op_name[214:218],
	65:  _Op_name[218:222],
	80:  _Op_name[222:227],
	81:  _Op_name[227:233],
	82:  _Op_name[233:241],
	112: _Op_name[241:249],
	113: _Op_name[249:255],
	114: _Op_name[255:266],
	115: _Op_name[266:275],
	116: _Op_name[275:290],
	117: _Op_name[290:302],
	118: _Op_name[302:312],
	119: _Op_name[312:328],
	128: _Op_name[328:332],
	129: _Op_name[332:343],
	130: _Op_name[343:357],
	131: _Op_name[357:372],
	136: _Op_name[372:381],
	137: _Op_name[381:390],
	138: _Op_name[390:399],
	139: _Op_name[399:408],
	140: _Op_name[408:418],
	141: _Op_name[418:428],
	142: _Op_name[428:438],
	143: _Op_name[438:449],
	144: _Op_name[449:460],
	192: _Op_name[460:466],
	255: _Op_name[466:472],
}

func (i Op) String() string {
	if str, ok := _Op_map[i]; ok {
		return str
	}
	return "Op(" + strconv.FormatInt(int64(i), 10) + ")"
}
